# Generated by Django 3.0.8 on 2020-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_add_items_and_orders_and_inventory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(upload_to='inventory/'),
        ),
    ]
